### ISSUE TITLE
When 3d secure = true, use no 3D card.  Transaction status on magento1 is successful

### ISSUE THREAD

**Issue by ken-liao** [goceevo/magento1-plugin#11]
When 3d secure = true,use no 3D card.Magento1  should be "YOUR ORDER HAS BEEN RECEIVED." page.
![image](https://user-images.githubusercontent.com/54881808/71333453-fed49480-2574-11ea-95b9-fc375ebbf3e8.png)
should not "AN ERROR OCCURRED IN THE PROCESS OF PAYMENT" page.
![image](https://user-images.githubusercontent.com/54881808/71333535-49561100-2575-11ea-9e94-8f17f46f89b7.png)

**Comment by spsinghats** [comment]
Yes because getting "Status ->Succeeded" in response from Ceevo and also in Ceevo Dashboard.

**Comment by spsinghats** [comment]
Getting transaction Id, status->Succeeded but we are not getting "message" in charge API response from Ceevo, also getting locationUrl and when we redirecting to locationUrl then we getting "payload" and not getting "HMACSHA256".
In this case checksum condition  failed and  getting us to Failure Page

**Comment by spsinghats** [comment]
In this case we are getting  "status->SUCCEEDED" in response from  but we are not getting "message" in charge API response from Ceevo, also getting locationUrl and when we redirecting to locationUrl then we are not getting "HMACSHA256".
In this case checksum condition failed and getting us to Failure Page

**Comment by spsinghats** [comment]
Please check updated code.

**Comment by ken-liao** [comment]
fix
