### ISSUE TITLE
Use Different Order Status For Successful / Not Successful Payments

### ISSUE THREAD

**Issue by sprankhub** [goceevo/magento1-plugin#5]
Currently, one can only define one order status, which is set no matter if the payment was successful or not. It should be possible to define two different order status: One for successful payments and one for not successful payments.

**Comment by danielpun** [comment]
fixed

**Comment by sprankhub** [comment]
I do not see that this is fixed @danielpun. I can still only define one order status:

![image](https://user-images.githubusercontent.com/930199/77511472-6d293b80-6e71-11ea-90f0-97e50b8cfb97.png)

**Comment by danielpun** [comment]
May I know where did you see this 'New order status'?

![image](https://user-images.githubusercontent.com/906936/77517482-29f1bb80-6eb7-11ea-82db-b3941d4d487f.png)

**Comment by sprankhub** [comment]
Exactly there. I can set only **one** new order status there. So no matter if the payment was successful or failed, the customer will see the same order status, e.g. "Processing". It would make much more sense to have the possibility to define another order status for failed payments, e.g. "Failed Payment".

**Comment by danielpun** [comment]
Are you using the latest version 1.2.8? As you see my screen capture, I have other status codes, and these are Magento default status codes

**Comment by sprankhub** [comment]
Yes, I am using the latest "version" (although it is not a real version, because it is not tagged, see #10). The status codes can be configured in the Magento backend. Hence, we have different ones than you have. This is not about the status codes, but about the possibility to define different status codes for **failed** and **successful** payments.

Current config:

    New order status: [STATUSES]

Expected config:

    Successful order status: [STATUSES]
    Failed order status: [STATUSES]
